services:
  ecourse-fork:
    image: ghcr.io/1024mb/ecourse-fork:latest
    container_name: ecourse-fork
    #ports:
    #  - 8090:8090
    volumes:
      - ./ecourse/pb_data:/app/pb_data
      - ./ecourse/pb_migrations:/app/pb_migrations
      - ./data/videos:/app/pb_public/videos
    env_file:
      - .env
    restart: unless-stopped

