name: Build and push container image on release

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        default: 'dev'
        type: string
  push:
    # branches:
    #   - main
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'
      - 'v[0-9]*.[0-9]*.[0-9]*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract supported PocketBase version
        id: extract_pb_version
        run: |
          PB_VERSION=$(grep -v '^$' pb/.pb.version | head -n1 | sed 's/^v//')
          echo "pb_version=$PB_VERSION" >> "$GITHUB_OUTPUT"

      # ---- MANUAL RUN ----
      - name: Build and push (manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PB_VERSION=${{ steps.extract_pb_version.outputs.pb_version }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Parse version from tag
        id: version
        if: ${{ github.event_name != 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/') }}
        run: |
          RAW="${GITHUB_REF#refs/tags/}"
          VERSION="${RAW#v}"
          
          MAJOR="${VERSION%%.*}"
          MINOR="${VERSION%.*}"
          PATCH="$VERSION"
          
          echo "major=$MAJOR" >> "$GITHUB_OUTPUT"
          echo "minor=$MINOR" >> "$GITHUB_OUTPUT"
          echo "patch=$PATCH" >> "$GITHUB_OUTPUT"

      # ---- TAG PUSH ----
      - name: Build and push image
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PB_VERSION=${{ steps.extract_pb_version.outputs.pb_version }}
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ github.sha }}
            ${{ github.repository }}:${{ steps.version.outputs.major }}
            ${{ github.repository }}:${{ steps.version.outputs.minor }}
            ${{ github.repository }}:${{ steps.version.outputs.patch }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.major }}
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.minor }}
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.patch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
